name: Publish NPM package
on:
  push:
    branches: [ 'master' ]
  release:
    types: [ published ]
  pull_request:

jobs:
  publish:
    uses: wavesplatform/publish-to-npm/.github/workflows/publish.yml@7d9462af686d83552d72097bf47a892e43d11f6e
    with:
      environment: NPMJS
      event_name: push
      test: true
    permissions:
      id-token: write
      contents: read
